# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
pr:
- master

jobs:
- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: windows
    buildPlatform: x64
    frameworks: [net35, net45, net472, net48, netcoreapp3.0, netcoreapp3.1]
    publishBuild: true

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: windows
    buildPlatform: x86
    frameworks: [net35, net45, net472, net48, netcoreapp3.0, netcoreapp3.1]

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: windows
    buildPlatform: x64
    runtimeType: mono
    frameworks: [net35, net45, net472, net48] # mono for .NET Core just delegates to actual .NET Core, so no need for mono .NET Core tests

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: windows
    buildPlatform: x86
    runtimeType: mono
    frameworks: [net35, net45, net472, net48] # mono for .NET Core just delegates to actual .NET Core, so no need for mono .NET Core tests

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: ubuntu
    buildPlatform: x64
    frameworks: [net35, net45, net472, net48, netcoreapp3.0, netcoreapp3.1]

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: ubuntu
    buildPlatform: x86
    frameworks: [net35, net45, net472, net48, netcoreapp3.0, netcoreapp3.1]

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: macOS
    buildPlatform: x64
    frameworks: [net35, net45, net472, net48, netcoreapp3.0, netcoreapp3.1]

- template: azure-pipelines-job-template.yml
  parameters:
    osPlatform: macOS
    buildPlatform: x86
    frameworks: [net35, net45, net472, net48, netcoreapp3.0, netcoreapp3.1]
